# Generated by Django 5.2.6 on 2025-09-14 00:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line_type', models.CharField(choices=[('Transect', 'Transect'), ('MouseLine', 'MouseLine')], max_length=20)),
                ('start_station_id', models.CharField(max_length=50)),
                ('end_station_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_station_id', models.CharField(max_length=50)),
                ('simple_issue', models.CharField(choices=[('Complicated', 'Complicated'), ('MissingStation', 'MissingStation'), ('MissingHoop', 'MissingHoop'), ('MissingWire', 'MissingWire'), ('SlightlyRotten', 'SlightlyRotten'), ('VeryRotten', 'VeryRotten'), ('NeedsReplacing', 'NeedsReplacing'), ('NeedsRope', 'NeedsRope'), ('RopeOnDeadTree', 'RopeOnDeadTree'), ('RequiresChainSaw', 'RequiresChainSaw'), ('Flora', 'Flora'), ('Fauna', 'Fauna')], max_length=20)),
                ('station_type', models.CharField(choices=[('NovaCoil', 'NovaCoil'), ('NovaCoilBoxed', 'NovaCoilBoxed'), ('WoodenBox', 'WoodenBox'), ('WeirdBox', 'WeirdBox')], max_length=20)),
                ('end_station_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='issue_photos/')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='worktracking.line')),
            ],
        ),
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_station_id', models.CharField(max_length=50)),
                ('end_station_id', models.CharField(max_length=50)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outings', to='worktracking.line')),
                ('participants', models.ManyToManyField(to='worktracking.teammember')),
            ],
        ),
    ]
