# Generated by Django 5.2.6 on 2025-09-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='completion_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Partial', 'Partially Worked On')], default='Completed', max_length=20),
        ),
    ]
