# Generated by Django 5.2.6 on 2025-09-14 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0002_outing_completion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outing',
            name='end_station_id',
        ),
        migrations.RemoveField(
            model_name='outing',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='outing',
            name='start_station_id',
        ),
        migrations.RemoveField(
            model_name='outing',
            name='start_time',
        ),
        migrations.AddField(
            model_name='outing',
            name='date',
            field=models.DateField(default="20200101"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outing',
            name='number_of_workers',
            field=models.PositiveIntegerField(default=1, help_text="Number of workers (use when individual names aren't known)"),
        ),
        migrations.AlterField(
            model_name='outing',
            name='hours',
            field=models.DecimalField(decimal_places=2, help_text='Total hours worked during this outing', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='outing',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Specific team members who participated (if known)', to='worktracking.teammember'),
        ),
    ]
