# Generated by Django 5.2.6 on 2025-09-14 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0003_remove_outing_end_station_id_remove_outing_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='outing',
            field=models.ForeignKey(blank=True, help_text='The outing during which this issue was found', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='worktracking.outing'),
        ),
    ]
