# Generated by Django 5.2.6 on 2025-09-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0004_issue_outing'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='end_station_id',
            field=models.CharField(blank=True, help_text='Ending station ID for this outing (subset of the line)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outing',
            name='start_station_id',
            field=models.CharField(blank=True, help_text='Starting station ID for this outing (subset of the line)', max_length=50, null=True),
        ),
    ]
