# Generated by Django 5.2.6 on 2025-09-14 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0005_outing_end_station_id_outing_start_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outing',
            name='number_of_workers',
            field=models.DecimalField(decimal_places=1, default=1, help_text='Number of workers (can be decimal, e.g., 2.5 if someone left early)', max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
