# Generated by Django 5.2.6 on 2025-09-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0006_alter_outing_number_of_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionReport',
            fields=[
            ],
            options={
                'verbose_name': 'Completion Report',
                'verbose_name_plural': 'Completion Report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('worktracking.line',),
        ),
    ]
