# Generated by Django 5.2.6 on 2025-09-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0007_completionreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='simple_issue',
            field=models.CharField(choices=[('Complicated', 'Complicated'), ('MissingStation', 'Missing Station'), ('MissingHoop', 'Missing Hoop'), ('MissingWire', 'Missing Wire'), ('SlightlyRotten', 'Slightly Rotten'), ('VeryRotten', 'Very Rotten'), ('NeedsReplacing', 'Needs Replacing'), ('NeedsRope', 'NeedsRope'), ('NeedsFrequentAttn', 'Needs Frequent Attention'), ('RopeOnDeadTree', 'Rope On Dead Tree'), ('RequiresChainsaw', 'Requires Chainsaw'), ('Flora', 'Flora'), ('Fauna', 'Fauna'), ('Weed', 'Weed')], max_length=20),
        ),
    ]
