# Generated by Django 5.2.6 on 2025-09-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0008_alter_issue_simple_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='start_station_id',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='line',
            name='end_station_id',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='line',
            name='start_station_id',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='outing',
            name='end_station_id',
            field=models.CharField(blank=True, help_text='Ending station ID for this outing (subset of the line)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='outing',
            name='start_station_id',
            field=models.CharField(blank=True, help_text='Starting station ID for this outing (subset of the line)', max_length=5, null=True),
        ),
    ]
