# Generated by Django 5.2.6 on 2025-09-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0009_alter_issue_start_station_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='end_station_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='station_type',
            field=models.CharField(choices=[('NovaCoil', 'NovaCoil'), ('NovaCoilBoxed', 'NovaCoilBoxed'), ('WoodenBox', 'WoodenBox'), ('WeirdBox', 'WeirdBox'), ('NA', 'N/A')], max_length=20),
        ),
    ]
