# Generated by Django 5.2.6 on 2025-09-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0010_alter_issue_end_station_id_alter_issue_station_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='station_type',
            field=models.CharField(choices=[('NovaCoil', 'NovaCoil'), ('NovaCoilBoxed', 'NovaCoilBoxed'), ('WoodenBox', 'WoodenBox'), ('WeirdBox', 'WeirdBox'), ('NA', 'N/A')], max_length=20, null=True),
        ),
    ]
