# Generated by Django 5.2.6 on 2025-09-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0012_alter_issue_station_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('NeedsWork', 'Needs Work'), ('Progressing', 'Progressing'), ('NeedsRepeating', 'Needs Repeating')], default='NeedsWork', max_length=20),
        ),
    ]
