# Generated by Django 5.2.6 on 2025-09-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0013_issue_issue_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='simple_issue',
            new_name='issue_type',
        ),
    ]
