# Generated by Django 5.2.6 on 2025-09-18 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0014_rename_simple_issue_to_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('Complicated', 'Complicated'), ('MissingStation', 'Missing Station'), ('MissingHoop', 'Missing Hoop'), ('MissingWire', 'Missing Wire'), ('SlightlyRotten', 'Slightly Rotten'), ('VeryRotten', 'Very Rotten'), ('NeedsReplacing', 'Needs Replacing'), ('NeedsRope', 'Needs Rope'), ('NeedsFrequentAttn', 'Needs Frequent Attention'), ('RopeOnDeadTree', 'Rope On Dead Tree'), ('RequiresChainsaw', 'Requires Chainsaw'), ('Flora', 'Flora'), ('Fauna', 'Fauna'), ('Weed', 'Weed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='outing',
            field=models.ForeignKey(blank=True, help_text='The outing during which this issue was found (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='worktracking.outing'),
        ),
    ]
