# Generated by Django 5.2.6 on 2025-10-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0016_alter_line_options_alter_issue_issue_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='last_action_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
