# Generated by Django 5.2.6 on 2025-10-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0017_issue_last_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('NeedsWork', 'Needs Work'), ('Progressing', 'Progressing'), ('NeedsRepeating', 'Needs Repeating'), ('Notice', 'Notice (no action req.)'), ('NoActionReq', 'No action req.')], default='NeedsWork', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('Complicated', 'Complicated'), ('MissingStation', 'Missing Station'), ('MissingHoop', 'Missing Hoop'), ('MissingWire', 'Missing Wire'), ('SlightlyRotten', 'Slightly Rotten'), ('VeryRotten', 'Very Rotten'), ('NeedsClearing', 'Needs Clearing'), ('NeedsReplacing', 'Needs Replacing'), ('NeedsRope', 'Needs Rope'), ('NeedsFrequentAttn', 'Needs Frequent Attention'), ('RopeOnDeadTree', 'Rope On Dead Tree'), ('RequiresChainsaw', 'Requires Chainsaw'), ('Flora', 'Flora'), ('Fauna', 'Fauna'), ('Weed', 'Weed'), ('Safety', 'Safety'), ('Note', 'Note')], max_length=20),
        ),
    ]
