# Generated by Django 5.2.6 on 2025-10-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0019_alter_issue_issue_status_alter_issue_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('Complicated', 'Complicated'), ('MissingStation', 'Missing Station'), ('MissingHoop', 'Missing Hoop'), ('MissingLid', 'Missing Lid'), ('MissingWire', 'Missing Wire'), ('MissingMesh', 'Missing Mesh'), ('NeedsPlasticTub', 'Needs a Plastic Tub'), ('NeedsReplacing', 'Needs Replacing'), ('SlightlyRotten', 'Slightly Rotten'), ('VeryRotten', 'Very Rotten'), ('NeedsClearing', 'Needs Clearing'), ('NeedsRope', 'Needs Rope'), ('NeedsFrequentAttn', 'Needs Frequent Attention'), ('RopeOnDeadTree', 'Rope On Dead Tree'), ('RequiresChainsaw', 'Requires Chainsaw'), ('Safety', 'Safety'), ('Flora', 'Flora'), ('Fauna', 'Fauna'), ('Weed', 'Weed'), ('Note', 'Note')], max_length=20),
        ),
    ]
