# Generated by Django 5.2.6 on 2025-10-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0021_alter_issue_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='origin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
