# Generated by Django 5.2.6 on 2025-10-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0022_issue_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='origin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
