# Generated by Django 5.2.6 on 2025-10-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0024_alter_issue_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
