# Generated by Django 5.2.6 on 2025-10-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0025_teammember_available_alter_teammember_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
