# Generated by Django 5.2.6 on 2025-10-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0026_alter_teammember_email_address_alter_teammember_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-available', 'name']},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='email_address',
        ),
    ]
