# Generated by Django 5.2.6 on 2025-10-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0027_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('LoginFailed', 'Login Failed')], max_length=20)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('username', models.CharField(max_length=256, null=True)),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
