# Generated by Django 5.2.6 on 2025-10-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0030_audit_delete_auditing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'verbose_name': 'User Login Activity', 'verbose_name_plural': 'User Login Activities'},
        ),
    ]
