# Generated by Django 5.2.6 on 2025-10-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0031_alter_audit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('Complicated', 'Complicated'), ('MissingStation', 'Missing Station'), ('MissingHoop', 'Missing Hoop'), ('MissingLid', 'Missing Lid'), ('MissingMesh', 'Missing Mesh'), ('Needs_New_ICC', 'Needs new ICC'), ('NeedsReplacing', 'Needs Replacing'), ('SlightlyRotten', 'Slightly Rotten'), ('VeryRotten', 'Very Rotten'), ('NeedsClearing', 'Needs Clearing'), ('NeedsRope', 'Needs Rope'), ('NeedsFrequentAttn', 'Needs Frequent Attention'), ('RopeOnDeadTree', 'Rope On Dead Tree'), ('RequiresChainsaw', 'Requires Chainsaw'), ('Safety', 'Safety'), ('Flora', 'Flora'), ('Fauna', 'Fauna'), ('Weed', 'Weed'), ('Baitout', 'Baitout'), ('Note', 'Note')], max_length=20),
        ),
    ]
