# Generated by Django 5.2.6 on 2025-10-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0035_issue_reported_by_alter_issue_issue_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
