# Generated by Django 5.2.6 on 2025-10-14 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0037_init_issue_datetimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 1, 12, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 1, 12, 0)),
            preserve_default=False,
        ),
    ]
