# Generated by Django 5.2.6 on 2025-10-14 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0038_alter_issue_created_at_alter_issue_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='last_action_date',
        ),
    ]
