# Generated by Django 5.2.6 on 2025-10-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0039_remove_issue_last_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='origin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
