# Generated by Django 5.2.6 on 2025-10-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0040_alter_issue_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='reported_by',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
