# Generated by Django 5.2.6 on 2025-10-16 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktracking', '0041_alter_issue_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='work_priority',
            field=models.IntegerField(blank=True, help_text='Priority for work 1..10, 1 is highest.', null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
